var musicfile=['source/1.mp3','source/2.mp3','source/3.mp3','source/4.mp3','source/5.mp3','source/6.mp3','source/7.mp3','source/8.mp3','source/9.mp3','source/10.mp3','source/11.mp3','source/12.mp3','source/13.mp3','source/14.mp3','source/15.mp3','source/16.mp3','source/17.mp3','source/18.mp3','source/19.mp3','source/20.mp3','source/21.mp3','source/22.mp3','source/23.mp3','source/24.mp3','source/25.mp3','source/26.mp3','source/27.mp3','source/28.mp3','source/29.mp3','source/30.mp3','source/31.mp3','source/32.mp3','source/33.mp3','source/34.mp3','source/35.mp3'];
var musicfiletit=[
				'李玉刚 - 刚好遇见你',
				'吴雨霏 - 生命树',
				'汪苏泷 - 小星星',
				'苏琛 - 最后一首情歌',
				'MC吴迪 - 我要的光荣',
				'SNH48 - 逐梦演艺圈',
				'阿杜 - 为爱投降',
				'艾福杰尼 - Together We Play',
				'白小白 - 只想说声爱你',
				'曾一鸣 - 会不会突然想起我',
				'陈雪凝 - 假装',
				'成龙 - 普通人',
				'鬼卞 - 读不完的热爱',
				'韩安旭 - 最痛的告白',
				'黑崎子 - Panama',
				'黑崎子 - 春风吹',
				'黑崎子 - 带你去旅行',
				'红花会PG ONE - Pentakill',
				'红花会PG ONE - 英雄归来',
				'胡夏 - 青春遗言',
				'胡彦斌 - Give me a chance',
				'胡彦斌 - 高手',
				'华晨宇 - 智商二五零',
				'黄子韬 - 想成为你',
				'辉子 - Bee With U',
				'吉克隽逸 - 一生所爱',
				'金志文 - 给我一点寂寞的时间',
				'金志文 - 哭给你听',
				'刘大美人 - 你是我爱的人',
				'鹿晗 - 追梦赤子心',
				'毛晓彤 - 遥远的诺言',
				'王奕心 - 情不变',
				'魏晨 - 星辰大海是你',
				'吴亦凡 - 我选择的路',
				'杨丞琳 - 青春住了谁',
				];